FATFS_REL_DIR := Lib/FatFs

C_SOURCES_FATFS += $(FATFS_REL_DIR)/ff.c

C_INCLUDES_FATFS += -I$(FATFS_REL_DIR)
C_INCLUDES_FATFS += -ILib/minimp4

C_SOURCES += $(C_SOURCES_FATFS)
C_INCLUDES += $(C_INCLUDES_FATFS)
